# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: posts.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'posts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bposts.proto\x12\x05posts\"0\n\x04Post\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\r\n\x05views\x18\x03 \x01(\x05\"\x07\n\x05\x45mpty\"\x14\n\x06PostId\x12\n\n\x02id\x18\x01 \x01(\t\"&\n\x08PostList\x12\x1a\n\x05posts\x18\x01 \x03(\x0b\x32\x0b.posts.Post2_\n\x0cPostsService\x12(\n\x07\x46indAll\x12\x0c.posts.Empty\x1a\x0f.posts.PostList\x12%\n\x07\x46indOne\x12\r.posts.PostId\x1a\x0b.posts.Postb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'posts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POST']._serialized_start=22
  _globals['_POST']._serialized_end=70
  _globals['_EMPTY']._serialized_start=72
  _globals['_EMPTY']._serialized_end=79
  _globals['_POSTID']._serialized_start=81
  _globals['_POSTID']._serialized_end=101
  _globals['_POSTLIST']._serialized_start=103
  _globals['_POSTLIST']._serialized_end=141
  _globals['_POSTSSERVICE']._serialized_start=143
  _globals['_POSTSSERVICE']._serialized_end=238
# @@protoc_insertion_point(module_scope)
